import type { FastifyInstance } from "fastify";
import { ZodError } from "zod";

import {
  MaulLineageConflictError,
  MaulProjectNotFoundError,
  type MaulProjectService,
} from "./service.js";
import { MAUL_RUNTIME_CONTRACTS } from "./runtime-contracts.js";

const statusForError = (error: unknown): number => {
  if (error instanceof MaulProjectNotFoundError) {
    return 404;
  }
  if (error instanceof MaulLineageConflictError) {
    return 409;
  }
  return 400;
};

const errorBody = (error: unknown): { error: string } => ({
  error:
    error instanceof ZodError
      ? error.issues.map((issue) => issue.message).join("; ")
      : error instanceof Error
        ? error.message
        : String(error),
});

const GOVERNED_RUNTIME_ONLY_ARTIFACT_TYPES = new Set([
  "planner_audit",
  "observation_snapshot",
  "candidate_narrative",
  "editorial_beat_map",
  "typography_motion_plan",
  "framing_camera_plan",
  "visual_plan",
  "dialogue_audio_plan",
  "capability_selection",
  "adapter_decision",
  "art_direction_plan",
  "context_assembly_plan",
  "shot_intent_matrix",
  "text_opportunity_plan",
  "revision_plan",
  "planning_bundle",
  "render_manifest",
  "quality_evidence_bundle",
]);

export const registerMaulProjectRoutes = (
  app: FastifyInstance,
  projects: MaulProjectService,
): void => {
  app.get("/api/maul/contracts", async () => MAUL_RUNTIME_CONTRACTS);

  app.post(
    "/api/maul/text-chunks/preview",
    {bodyLimit: 512 * 1024},
    async (req, reply) => {
      try {
        return await projects.previewTextChunks(req.body);
      } catch (error) {
        reply.code(statusForError(error));
        return errorBody(error);
      }
    },
  );

  app.get("/api/maul/treatment-catalog", async (_req, reply) => {
    try {
      return projects.getTreatmentCatalog();
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.post("/api/maul/projects", async (req, reply) => {
    try {
      const result = await projects.createProject(req.body);
      reply.code(201);
      return {
        ...result,
        urls: {
          project: `/api/maul/projects/${result.project.id}`,
          artifacts: `/api/maul/projects/${result.project.id}/artifacts`,
          audit: `/api/maul/projects/${result.project.id}/audit`,
          resume: `/api/maul/projects/${result.project.id}/resume`,
        },
      };
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.get("/api/maul/projects/:projectId", async (req, reply) => {
    try {
      const { projectId } = req.params as { projectId: string };
      return await projects.getProject(projectId);
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.post("/api/maul/projects/:projectId/resume", async (req, reply) => {
    try {
      const { projectId } = req.params as { projectId: string };
      return await projects.resumeProject(projectId, req.body);
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.post("/api/maul/projects/:projectId/artifacts", async (req, reply) => {
    try {
      const { projectId } = req.params as { projectId: string };
      const artifactRequest = req.body as {
        artifactType?: string;
        payload?: {
          evidence?: { qualityGate?: { releaseEligible?: boolean } };
        };
      };
      if (
        artifactRequest.artifactType &&
        GOVERNED_RUNTIME_ONLY_ARTIFACT_TYPES.has(artifactRequest.artifactType)
      ) {
        throw new MaulLineageConflictError(
          "Manual governed planning, authority, and render-manifest artifacts are forbidden; these records must be generated by the governed runtime and Manifest Compiler.",
        );
      }
      if (
        artifactRequest.artifactType === "export_artifact" &&
        artifactRequest.payload?.evidence?.qualityGate?.releaseEligible === true
      ) {
        throw new MaulLineageConflictError(
          "Manual quality-gate release authority is forbidden; only the governed post-render quality workflow may mark an export release-eligible.",
        );
      }
      const result = await projects.registerArtifact(projectId, req.body);
      reply.code(201);
      return result;
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.get("/api/maul/projects/:projectId/audit", async (req, reply) => {
    try {
      const { projectId } = req.params as { projectId: string };
      return await projects.getAudit(projectId);
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.post("/api/maul/projects/:projectId/references", async (req, reply) => {
    try {
      const { projectId } = req.params as { projectId: string };
      if (!req.isMultipart()) {
        const result = await projects.ingestReference(projectId, req.body);
        reply.code(201);
        return result;
      }

      let metadataJson = "";
      let upload:
        | { originalFilename: string; contentType: string; bytes: Buffer }
        | undefined;
      for await (const part of req.parts()) {
        if (part.type === "file") {
          if (part.fieldname !== "reference_file") {
            await part.toBuffer();
            continue;
          }
          upload = {
            originalFilename: part.filename || "reference.bin",
            contentType: part.mimetype || "application/octet-stream",
            bytes: await part.toBuffer(),
          };
          continue;
        }
        if (part.fieldname === "metadata_json") {
          metadataJson = String(part.value ?? "");
        }
      }
      if (!metadataJson) {
        throw new Error(
          "Multipart reference ingestion requires metadata_json.",
        );
      }
      if (!upload) {
        throw new Error(
          "Multipart reference ingestion requires reference_file.",
        );
      }
      const result = await projects.ingestReference(
        projectId,
        JSON.parse(metadataJson) as unknown,
        upload,
      );
      reply.code(201);
      return result;
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.get("/api/maul/projects/:projectId/references", async (req, reply) => {
    try {
      const { projectId } = req.params as { projectId: string };
      const query = req.query as {
        q?: string;
        rightsStatus?: string;
        reviewStatus?: string;
      };
      return await projects.searchReferences(projectId, query);
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.post(
    "/api/maul/projects/:projectId/references/:artifactId/review",
    async (req, reply) => {
      try {
        const { projectId, artifactId } = req.params as {
          projectId: string;
          artifactId: string;
        };
        const result = await projects.reviewReference(
          projectId,
          artifactId,
          req.body,
        );
        reply.code(201);
        return result;
      } catch (error) {
        reply.code(statusForError(error));
        return errorBody(error);
      }
    },
  );

  app.get(
    "/api/maul/projects/:projectId/references/:artifactId/source",
    async (req, reply) => {
      try {
        const { projectId, artifactId } = req.params as {
          projectId: string;
          artifactId: string;
        };
        const source = await projects.getReferenceSource(projectId, artifactId);
        reply.header("Content-Type", source.contentType);
        reply.header("Content-Length", String(source.sizeBytes));
        reply.header(
          "Content-Disposition",
          `inline; filename="${source.originalFilename.replace(/"/g, "")}"`,
        );
        return reply.send(source.bytes);
      } catch (error) {
        reply.code(statusForError(error));
        return errorBody(error);
      }
    },
  );

  app.post(
    "/api/maul/projects/:projectId/editorial-timeline",
    async (req, reply) => {
      try {
        const { projectId } = req.params as { projectId: string };
        const result = await projects.createEditorialTimeline(
          projectId,
          req.body,
        );
        reply.code(201);
        return result;
      } catch (error) {
        reply.code(statusForError(error));
        return errorBody(error);
      }
    },
  );

  app.post("/api/maul/projects/:projectId/treatments", async (req, reply) => {
    try {
      const { projectId } = req.params as { projectId: string };
      const result = await projects.createTreatmentCatalog(projectId, req.body);
      reply.code(201);
      return result;
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.post("/api/maul/projects/:projectId/candidates", async (req, reply) => {
    try {
      const { projectId } = req.params as { projectId: string };
      const result = await projects.createCandidates(projectId, req.body);
      reply.code(201);
      return result;
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.post(
    "/api/maul/projects/:projectId/planning-bundles",
    async (req, reply) => {
      try {
        const { projectId } = req.params as { projectId: string };
        const result = await projects.createPlanningBundle(projectId, req.body);
        reply.code(201);
        return result;
      } catch (error) {
        reply.code(statusForError(error));
        return errorBody(error);
      }
    },
  );
  app.post("/api/maul/projects/:projectId/reviews", async (req, reply) => {
    try {
      const { projectId } = req.params as { projectId: string };
      const result = await projects.reviewCandidate(projectId, req.body);
      reply.code(201);
      return result;
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.post("/api/maul/projects/:projectId/renders", async (req, reply) => {
    try {
      const { projectId } = req.params as { projectId: string };
      const result = await projects.renderShort(projectId, req.body);
      reply.code(201);
      return result;
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.get(
    "/api/maul/projects/:projectId/exports/:artifactId/file",
    async (req, reply) => {
      try {
        const { projectId, artifactId } = req.params as {
          projectId: string;
          artifactId: string;
        };
        const file = await projects.getExportFile(projectId, artifactId);
        reply.header("Content-Type", file.contentType);
        reply.header("Content-Length", String(file.sizeBytes));
        reply.header(
          "Content-Disposition",
          `attachment; filename="${file.filename.replace(/"/g, "")}"`,
        );
        return reply.send(file.bytes);
      } catch (error) {
        reply.code(statusForError(error));
        return errorBody(error);
      }
    },
  );

  app.post("/api/maul/projects/:projectId/thumbnails", async (req, reply) => {
    try {
      const { projectId } = req.params as { projectId: string };
      const result = await projects.createThumbnails(projectId, req.body);
      reply.code(201);
      return result;
    } catch (error) {
      reply.code(statusForError(error));
      return errorBody(error);
    }
  });

  app.post(
    "/api/maul/projects/:projectId/thumbnails/:artifactId/review",
    async (req, reply) => {
      try {
        const { projectId, artifactId } = req.params as {
          projectId: string;
          artifactId: string;
        };
        const result = await projects.reviewThumbnail(
          projectId,
          artifactId,
          req.body,
        );
        reply.code(201);
        return result;
      } catch (error) {
        reply.code(statusForError(error));
        return errorBody(error);
      }
    },
  );

  app.get(
    "/api/maul/projects/:projectId/thumbnails/:artifactId/file",
    async (req, reply) => {
      try {
        const { projectId, artifactId } = req.params as {
          projectId: string;
          artifactId: string;
        };
        const file = await projects.getThumbnailFile(projectId, artifactId);
        reply.header("Content-Type", file.contentType);
        reply.header("Content-Length", String(file.sizeBytes));
        reply.header(
          "Content-Disposition",
          `inline; filename="${file.filename.replace(/"/g, "")}"`,
        );
        return reply.send(file.bytes);
      } catch (error) {
        reply.code(statusForError(error));
        return errorBody(error);
      }
    },
  );
};
