export type MetadataFieldType =
  | "string"
  | "number"
  | "boolean"
  | "enum"
  | "string[]"
  | "object"
  | "number[]";

export type MetadataCatalogEntry = {
  key_path: string;
  group: string;
  label: string;
  type: MetadataFieldType;
  enum_values?: string[];
  required_when: string;
  default_behavior: string;
  help_text: string;
};

const buildEntries = (
  group: string,
  entries: Array<{
    key: string;
    label: string;
    type: MetadataFieldType;
    enum_values?: string[];
    required_when?: string;
    default_behavior: string;
    help_text: string;
  }>
): MetadataCatalogEntry[] => {
  return entries.map((entry) => ({
    key_path: `${group}.${entry.key}`,
    group,
    label: entry.label,
    type: entry.type,
    enum_values: entry.enum_values,
    required_when: entry.required_when ?? "optional",
    default_behavior: entry.default_behavior,
    help_text: entry.help_text
  }));
};

export const METADATA_CATALOG_ENTRIES: MetadataCatalogEntry[] = [
  ...buildEntries("job", [
    {
      key: "job_id",
      label: "Job ID",
      type: "string",
      default_behavior: "Generated by backend at intake.",
      help_text: "Stable central identifier for every edit request."
    },
    {
      key: "job_version",
      label: "Job Version",
      type: "string",
      default_behavior: "Defaults to service schema version.",
      help_text: "Schema version for the shared job record."
    },
    {
      key: "request_timestamp",
      label: "Request Timestamp",
      type: "string",
      default_behavior: "Generated on receipt.",
      help_text: "ISO timestamp when the job was created."
    },
    {
      key: "processing_mode",
      label: "Processing Mode",
      type: "enum",
      enum_values: ["draft", "fast", "full"],
      default_behavior: "Defaults to full.",
      help_text: "Requested processing depth for the job."
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      enum_values: ["received", "analyzing", "metadata_ready", "plan_ready", "execution_ready", "audio_render", "ranking", "completed", "failed"],
      default_behavior: "Managed by backend state machine.",
      help_text: "Current lifecycle state of the job."
    }
  ]),
  ...buildEntries("source_media", [
    {
      key: "source_filename",
      label: "Source Filename",
      type: "string",
      default_behavior: "Derived from uploaded file or reference.",
      help_text: "Original file name or referenced media name."
    },
    {
      key: "source_filesize_bytes",
      label: "Source Filesize",
      type: "number",
      default_behavior: "Derived from local file stat when available.",
      help_text: "Uploaded video size in bytes."
    },
    {
      key: "source_duration_ms",
      label: "Source Duration",
      type: "number",
      default_behavior: "Derived from ffprobe when available.",
      help_text: "Source video duration in milliseconds."
    },
    {
      key: "source_width",
      label: "Source Width",
      type: "number",
      default_behavior: "Derived from media probe.",
      help_text: "Video pixel width."
    },
    {
      key: "source_height",
      label: "Source Height",
      type: "number",
      default_behavior: "Derived from media probe.",
      help_text: "Video pixel height."
    },
    {
      key: "source_aspect_ratio",
      label: "Source Aspect Ratio",
      type: "string",
      default_behavior: "Derived from width and height.",
      help_text: "Normalized aspect ratio string such as 9:16."
    },
    {
      key: "source_fps",
      label: "Source FPS",
      type: "number",
      default_behavior: "Derived from media probe or defaults to 30.",
      help_text: "Frames per second for the source media."
    },
    {
      key: "source_has_audio",
      label: "Has Audio",
      type: "boolean",
      default_behavior: "Assumed true for uploaded video unless probe says otherwise.",
      help_text: "Whether the source media includes an audio track."
    },
    {
      key: "source_storage_uri",
      label: "Source Storage URI",
      type: "string",
      default_behavior: "Filled with local persisted path in v1.",
      help_text: "Backend-resolved storage location for the source media."
    }
  ]),
  ...buildEntries("derived_technical", [
    {
      key: "format_family",
      label: "Format Family",
      type: "enum",
      enum_values: ["vertical", "horizontal", "square", "unknown"],
      default_behavior: "Derived from aspect ratio.",
      help_text: "High-level format family classification."
    },
    {
      key: "resolution_family",
      label: "Resolution Family",
      type: "enum",
      enum_values: ["sd", "hd", "fhd", "uhd", "unknown"],
      default_behavior: "Derived from media dimensions.",
      help_text: "Bucketed resolution label."
    },
    {
      key: "duration_bucket",
      label: "Duration Bucket",
      type: "enum",
      enum_values: ["micro", "short", "medium", "long"],
      default_behavior: "Derived from source duration.",
      help_text: "Coarse duration bucket used for defaults."
    },
    {
      key: "processing_weight_score",
      label: "Processing Weight",
      type: "number",
      default_behavior: "Derived from media complexity and duration.",
      help_text: "Rough cost estimate used for queueing and defaults."
    },
    {
      key: "fast_path_eligible",
      label: "Fast Path Eligible",
      type: "boolean",
      default_behavior: "Derived from duration and asset complexity.",
      help_text: "Whether the job can use lightweight defaults."
    },
    {
      key: "requires_caption_alignment",
      label: "Requires Caption Alignment",
      type: "boolean",
      default_behavior: "Enabled when transcript timing is needed.",
      help_text: "Whether caption alignment work must run."
    },
    {
      key: "requires_entity_scan",
      label: "Requires Entity Scan",
      type: "boolean",
      default_behavior: "Defaults to true when transcript or prompt text exists.",
      help_text: "Whether enrichment candidate extraction should run."
    }
  ]),
  ...buildEntries("user_intent", [
    {
      key: "raw_user_prompt",
      label: "Raw User Prompt",
      type: "string",
      default_behavior: "Copied from intake.",
      help_text: "Unmodified user request text."
    },
    {
      key: "intent_summary",
      label: "Intent Summary",
      type: "string",
      default_behavior: "Synthesized from prompt and media.",
      help_text: "Short backend summary of the editing ask."
    },
    {
      key: "content_type",
      label: "Content Type",
      type: "enum",
      enum_values: ["talking_head", "educational", "promo", "documentary", "social_clip", "podcast", "commentary"],
      default_behavior: "Defaults to talking_head when unspecified.",
      help_text: "High-level video category."
    },
    {
      key: "tone_target",
      label: "Tone Target",
      type: "string",
      default_behavior: "Defaults to cinematic-premium-clean.",
      help_text: "Creative tone the planner should maintain."
    },
    {
      key: "pace_target",
      label: "Pace Target",
      type: "enum",
      enum_values: ["slow", "medium", "high"],
      default_behavior: "Derived from prompt language and platform cues.",
      help_text: "Requested pacing intensity."
    },
    {
      key: "target_platform",
      label: "Target Platform",
      type: "enum",
      enum_values: ["shorts", "tiktok", "reels", "youtube", "generic"],
      default_behavior: "Defaults to generic.",
      help_text: "Target distribution surface when known."
    },
    {
      key: "editing_style_keywords",
      label: "Editing Style Keywords",
      type: "string[]",
      default_behavior: "Extracted from prompt cues.",
      help_text: "Style descriptors that influence presets."
    }
  ]),
  ...buildEntries("output", [
    {
      key: "output_formats_requested",
      label: "Output Formats",
      type: "string[]",
      default_behavior: "Defaults to mp4.",
      help_text: "Requested output container list."
    },
    {
      key: "output_primary_aspect_ratio",
      label: "Primary Aspect Ratio",
      type: "string",
      default_behavior: "Derived from source media or target platform.",
      help_text: "Main render aspect ratio target."
    },
    {
      key: "output_resolution_target",
      label: "Resolution Target",
      type: "string",
      default_behavior: "Derived from source media.",
      help_text: "Main render resolution target."
    },
    {
      key: "output_fps_target",
      label: "FPS Target",
      type: "number",
      default_behavior: "Derived from source media or 30.",
      help_text: "Target export frame rate."
    },
    {
      key: "output_preview_required",
      label: "Preview Required",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether the job should produce a preview artifact."
    },
    {
      key: "output_final_required",
      label: "Final Required",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether the job should produce a final artifact when renderer exists."
    }
  ]),
  ...buildEntries("timing_pacing", [
    {
      key: "silence_removal_enabled",
      label: "Silence Removal",
      type: "boolean",
      default_behavior: "Defaults to true for high-pace content.",
      help_text: "Whether silence tightening should run."
    },
    {
      key: "silence_mode",
      label: "Silence Mode",
      type: "enum",
      enum_values: ["remove", "tighten", "preserve"],
      default_behavior: "Defaults to tighten.",
      help_text: "How silence should be handled."
    },
    {
      key: "minimum_pause_ms",
      label: "Minimum Pause",
      type: "number",
      default_behavior: "Defaults to 120ms.",
      help_text: "Shortest pause the pacing system should keep."
    },
    {
      key: "maximum_pause_after_tightening_ms",
      label: "Max Tightened Pause",
      type: "number",
      default_behavior: "Defaults to 350ms.",
      help_text: "Maximum pause length allowed after pacing cleanup."
    },
    {
      key: "speech_rate_estimate",
      label: "Speech Rate",
      type: "number",
      default_behavior: "Derived from transcript words and duration when available.",
      help_text: "Estimated words-per-minute figure."
    },
    {
      key: "pacing_style",
      label: "Pacing Style",
      type: "string",
      default_behavior: "Defaults to premium-tight.",
      help_text: "Named pacing preset family."
    }
  ]),
  ...buildEntries("transcript_language", [
    {
      key: "transcript_available",
      label: "Transcript Available",
      type: "boolean",
      default_behavior: "Derived from intake or transcription stage.",
      help_text: "Whether a transcript exists for the job."
    },
    {
      key: "transcript_source",
      label: "Transcript Source",
      type: "enum",
      enum_values: ["provided", "cache", "assemblyai", "missing"],
      default_behavior: "Set by transcript resolution stage.",
      help_text: "Where the transcript came from."
    },
    {
      key: "transcript_language",
      label: "Transcript Language",
      type: "string",
      default_behavior: "Defaults to en.",
      help_text: "Language code for the transcript."
    },
    {
      key: "transcript_confidence",
      label: "Transcript Confidence",
      type: "number",
      default_behavior: "Derived from word confidences or heuristic defaults.",
      help_text: "Aggregate transcript confidence score."
    },
    {
      key: "word_timestamps_available",
      label: "Word Timestamps",
      type: "boolean",
      default_behavior: "True when transcript words include timing.",
      help_text: "Whether word-level timestamps are present."
    },
    {
      key: "speaker_diarization_available",
      label: "Diarization Available",
      type: "boolean",
      default_behavior: "Defaults to false in v1.",
      help_text: "Whether speaker separation data is available."
    },
    {
      key: "keyword_candidates",
      label: "Keyword Candidates",
      type: "string[]",
      default_behavior: "Derived from transcript and prompt text.",
      help_text: "Top candidate keywords for planning and enrichment."
    },
    {
      key: "named_entity_candidates",
      label: "Named Entity Candidates",
      type: "string[]",
      default_behavior: "Derived from prompt and transcript analysis.",
      help_text: "Potential named entities worth enrichment review."
    }
  ]),
  ...buildEntries("entity_enrichment", [
    {
      key: "entity_scan_enabled",
      label: "Entity Scan Enabled",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether the enrichment scan should run."
    },
    {
      key: "entity_detection_confidence_threshold",
      label: "Entity Confidence Threshold",
      type: "number",
      default_behavior: "Defaults to 0.72.",
      help_text: "Minimum confidence for considering an entity candidate."
    },
    {
      key: "entity_visual_relevance_threshold",
      label: "Visual Relevance Threshold",
      type: "number",
      default_behavior: "Defaults to 0.68.",
      help_text: "Minimum visual relevance needed for source candidacy."
    },
    {
      key: "entity_fetch_priority_threshold",
      label: "Fetch Priority Threshold",
      type: "number",
      default_behavior: "Defaults to 0.7.",
      help_text: "Minimum combined priority to mark a candidate as sourceable."
    },
    {
      key: "entity_fetch_enabled",
      label: "Entity Fetch Enabled",
      type: "boolean",
      default_behavior: "Defaults to true even though v1 does not execute remote fetches.",
      help_text: "Whether the planner should emit source-candidate intents."
    },
    {
      key: "entity_types_allowed",
      label: "Allowed Entity Types",
      type: "string[]",
      default_behavior: "Defaults to person, location, organization, event, product.",
      help_text: "Entity types that can become source candidates."
    },
    {
      key: "entity_to_fallback_mapping",
      label: "Entity Fallback Mapping",
      type: "object",
      default_behavior: "Defaults to fixed v1 fallback strategies by entity type.",
      help_text: "Fallback treatment to use when visual sourcing is unavailable."
    },
    {
      key: "external_visual_insertions_enabled",
      label: "External Visual Insertions",
      type: "boolean",
      default_behavior: "Defaults to true at planning level.",
      help_text: "Whether the planner can propose external visual insertions."
    }
  ]),
  ...buildEntries("uploaded_assets", [
    {
      key: "user_assets_present",
      label: "Assets Present",
      type: "boolean",
      default_behavior: "Derived from intake.",
      help_text: "Whether the user attached any additional assets."
    },
    {
      key: "user_asset_count",
      label: "Asset Count",
      type: "number",
      default_behavior: "Derived from intake.",
      help_text: "Number of uploaded assets attached to the job."
    },
    {
      key: "user_asset_manifest",
      label: "Asset Manifest",
      type: "object",
      default_behavior: "Filled from saved inputs manifest.",
      help_text: "Detailed summary of user-provided asset files."
    },
    {
      key: "user_asset_types",
      label: "Asset Types",
      type: "string[]",
      default_behavior: "Derived from file extensions and mime types.",
      help_text: "Bucketed asset kinds such as image, video, audio, or transparent_png."
    },
    {
      key: "user_asset_labels",
      label: "Asset Labels",
      type: "string[]",
      default_behavior: "Derived from multipart labels or asset descriptors.",
      help_text: "Optional labels attached to uploaded assets."
    },
    {
      key: "user_asset_background_type",
      label: "Asset Background Type",
      type: "enum",
      enum_values: ["transparent", "solid", "unknown"],
      default_behavior: "Inferred when possible, else unknown.",
      help_text: "Whether an uploaded image likely has transparency."
    },
    {
      key: "user_asset_is_cutout_ready",
      label: "Cutout Ready",
      type: "boolean",
      default_behavior: "Inferred for png/webp assets.",
      help_text: "Whether the asset is likely usable as a cutout without more prep."
    },
    {
      key: "user_asset_usage_notes",
      label: "Asset Usage Notes",
      type: "string[]",
      default_behavior: "Defaults to empty.",
      help_text: "Additional usage guidance supplied with asset descriptors."
    }
  ]),
  ...buildEntries("typography", [
    {
      key: "typography_enabled",
      label: "Typography Enabled",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether typography overlays are allowed."
    },
    {
      key: "caption_mode",
      label: "Caption Mode",
      type: "enum",
      enum_values: ["full", "selective", "headline_only", "none"],
      default_behavior: "Defaults to selective.",
      help_text: "How much captioning should appear."
    },
    {
      key: "caption_style_profile",
      label: "Caption Profile",
      type: "enum",
      enum_values: ["slcp", "longform_svg_typography_v1", "longform_eve_typography_v1"],
      default_behavior: "Defaults to slcp.",
      help_text: "Primary caption style profile identifier."
    },
    {
      key: "typography_default_preset",
      label: "Typography Preset",
      type: "string",
      default_behavior: "Defaults to cinematic-premium-pack.",
      help_text: "High-level typography preset family."
    },
    {
      key: "font_family_primary",
      label: "Primary Font Family",
      type: "string",
      default_behavior: "Defaults to tall-sans premium stack.",
      help_text: "Main font stack for captions and emphasis cards."
    },
    {
      key: "font_family_secondary",
      label: "Secondary Font Family",
      type: "string",
      default_behavior: "Defaults to premium serif/script accent stack.",
      help_text: "Secondary accent font stack."
    },
    {
      key: "primary_font",
      label: "Primary Font Contract",
      type: "object",
      default_behavior: "Resolved by the backend typography bridge when a renderable font asset is available.",
      help_text: "Backend-selected primary font with source, role, browser URL, score, and materialized source records."
    },
    {
      key: "secondary_font",
      label: "Secondary Font Contract",
      type: "object",
      default_behavior: "Resolved by the backend typography bridge when a compatible support font is available.",
      help_text: "Backend-selected secondary font with source, role, browser URL, score, and materialized source records."
    },
    {
      key: "primary_font_browser_url",
      label: "Primary Font Browser URL",
      type: "string",
      default_behavior: "Empty unless the typography bridge materializes a browser-safe font asset.",
      help_text: "Root-relative URL that the browser can use in @font-face rules for the primary font."
    },
    {
      key: "secondary_font_browser_url",
      label: "Secondary Font Browser URL",
      type: "string",
      default_behavior: "Empty unless the typography bridge materializes a browser-safe support font asset.",
      help_text: "Root-relative URL that the browser can use in @font-face rules for the secondary font."
    },
    {
      key: "font_face_css",
      label: "Font Face CSS",
      type: "string",
      default_behavior: "Generated by the typography bridge when materialized font URLs exist.",
      help_text: "CSS @font-face blocks for the selected typography assets."
    },
    {
      key: "font_pairing_score",
      label: "Font Pairing Score",
      type: "number",
      default_behavior: "Null unless the typography bridge can score the selected pair.",
      help_text: "Normalized confidence score for the selected font pairing."
    },
    {
      key: "font_pairing_source",
      label: "Font Pairing Source",
      type: "enum",
      enum_values: ["zilliz", "local", "system"],
      default_behavior: "Defaults to system when no retrieved or local font asset is available.",
      help_text: "Selection source used by the backend typography bridge."
    },
    {
      key: "font_pairing_query",
      label: "Font Pairing Query",
      type: "string",
      default_behavior: "Built from prompt, intent, platform, and typography profile.",
      help_text: "The semantic descriptor used to retrieve or rank font candidates."
    },
    {
      key: "font_graph_used",
      label: "Font Graph Used",
      type: "boolean",
      default_behavior: "False when the bridge falls back to system fonts.",
      help_text: "Whether the backend typography bridge used a retrieved or local font intelligence path."
    },
    {
      key: "font_fallback_used",
      label: "Font Fallback Used",
      type: "boolean",
      default_behavior: "True when Zilliz retrieval is unavailable or incomplete.",
      help_text: "Whether the bridge had to leave the primary Zilliz retrieval path."
    },
    {
      key: "font_fallback_reasons",
      label: "Font Fallback Reasons",
      type: "string[]",
      default_behavior: "Empty when the primary retrieved font path fully succeeds.",
      help_text: "Visible reasons explaining any typography asset fallback."
    },
    {
      key: "font_role_styles",
      label: "Font Role Styles",
      type: "object",
      default_behavior: "Generated by the typography bridge.",
      help_text: "Role-based CSS values for premium headline/support typography treatment."
    },
    {
      key: "keyword_emphasis_enabled",
      label: "Keyword Emphasis",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether keywords can receive special typography emphasis."
    },
    {
      key: "kinetic_text_enabled",
      label: "Kinetic Text",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether animated typography treatments are allowed."
    },
    {
      key: "fallback_text_card_style",
      label: "Fallback Text Card Style",
      type: "string",
      default_behavior: "Defaults to animated-name-card-premium.",
      help_text: "Text card style used when a visual fetch cannot be satisfied."
    }
  ]),
  ...buildEntries("motion_graphics", [
    {
      key: "motion_graphics_enabled",
      label: "Motion Graphics Enabled",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether motion graphics can be added."
    },
    {
      key: "motion_graphics_intensity",
      label: "Motion Intensity",
      type: "enum",
      enum_values: ["minimal", "restrained", "medium", "high"],
      default_behavior: "Defaults to restrained.",
      help_text: "Intensity level for motion accents."
    },
    {
      key: "motion_graphics_style_family",
      label: "Motion Style Family",
      type: "string",
      default_behavior: "Defaults to restrained-premium-accent.",
      help_text: "Selected motion graphics language."
    },
    {
      key: "motion_asset_selection_mode",
      label: "Motion Asset Selection",
      type: "enum",
      enum_values: ["preset", "auto", "user_driven"],
      default_behavior: "Defaults to preset.",
      help_text: "How motion asset selection should be handled."
    },
    {
      key: "motion_safe_area_rules",
      label: "Motion Safe Area Rules",
      type: "string",
      default_behavior: "Defaults to caption-safe-priority.",
      help_text: "Rule bundle for keeping motion out of reserved text space."
    },
    {
      key: "motion_vs_caption_priority",
      label: "Motion vs Caption Priority",
      type: "enum",
      enum_values: ["caption_first", "balanced", "motion_first"],
      default_behavior: "Defaults to caption_first.",
      help_text: "Conflict-resolution priority between captions and motion."
    },
    {
      key: "accent_graphics_enabled",
      label: "Accent Graphics",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether subtle accent graphics are allowed."
    },
    {
      key: "motion_mode",
      label: "Motion Mode",
      type: "enum",
      enum_values: ["quiet", "balanced", "aggressive"],
      default_behavior: "Defaults to balanced.",
      help_text: "Overall editorial motion posture for the timeline."
    },
    {
      key: "motion_asset_density_target",
      label: "Motion Asset Density Target",
      type: "number",
      default_behavior: "Defaults to a restrained per-minute budget.",
      help_text: "Target number of motion cues per minute."
    },
    {
      key: "motion_repetition_penalty",
      label: "Motion Repetition Penalty",
      type: "number",
      default_behavior: "Defaults to a moderate repetition penalty.",
      help_text: "Penalty applied when a motion asset repeats too quickly."
    },
    {
      key: "motion_emphasis_threshold",
      label: "Motion Emphasis Threshold",
      type: "number",
      default_behavior: "Defaults to a mid/high threshold.",
      help_text: "Minimum emphasis score needed before a motion asset can activate."
    },
    {
      key: "motion_clutter_threshold",
      label: "Motion Clutter Threshold",
      type: "number",
      default_behavior: "Defaults to a conservative clutter ceiling.",
      help_text: "Threshold used to suppress motion when the frame is already busy."
    },
    {
      key: "motion_min_spacing_between_heavy_assets_ms",
      label: "Heavy Asset Spacing",
      type: "number",
      default_behavior: "Defaults to a generous spacing window.",
      help_text: "Minimum spacing between heavier motion events."
    }
  ]),
  ...buildEntries("layout_collision", [
    {
      key: "subject_safe_zones",
      label: "Subject Safe Zones",
      type: "object",
      default_behavior: "Defaults to center-safe heuristics.",
      help_text: "Regions that should be preserved for visible subjects."
    },
    {
      key: "caption_reserved_zones",
      label: "Caption Reserved Zones",
      type: "object",
      default_behavior: "Defaults to lower-third safe layout.",
      help_text: "Regions reserved for captions and text cards."
    },
    {
      key: "motion_reserved_zones",
      label: "Motion Reserved Zones",
      type: "object",
      default_behavior: "Defaults to peripheral accent zones.",
      help_text: "Regions where motion overlays are allowed."
    },
    {
      key: "overlay_collision_policy",
      label: "Collision Policy",
      type: "string",
      default_behavior: "Defaults to prioritize-captions-then-subject.",
      help_text: "Primary conflict-resolution policy for overlays."
    },
    {
      key: "caption_priority_level",
      label: "Caption Priority Level",
      type: "number",
      default_behavior: "Defaults to 100.",
      help_text: "Numeric priority used during layout conflict resolution."
    },
    {
      key: "reframe_enabled",
      label: "Reframe Enabled",
      type: "boolean",
      default_behavior: "Defaults to false in v1.",
      help_text: "Whether reframing is allowed."
    },
    {
      key: "visual_clutter_limit",
      label: "Visual Clutter Limit",
      type: "enum",
      enum_values: ["low", "medium", "high"],
      default_behavior: "Defaults to low.",
      help_text: "Allowed clutter budget for simultaneous overlays."
    },
    {
      key: "subtitle_protection_margin_px",
      label: "Subtitle Protection Margin",
      type: "number",
      default_behavior: "Defaults to a generous subtitle-safe margin.",
      help_text: "Margin to keep motion away from subtitle zones."
    },
    {
      key: "face_safe_margin_px",
      label: "Face Safe Margin",
      type: "number",
      default_behavior: "Defaults to a conservative face-safe margin.",
      help_text: "Margin to keep motion away from subjects and faces."
    }
  ]),
  ...buildEntries("audio", [
    {
      key: "audio_cleanup_enabled",
      label: "Audio Cleanup",
      type: "boolean",
      default_behavior: "Defaults to true when audio exists.",
      help_text: "Whether audio cleanup should run."
    },
    {
      key: "noise_reduction_enabled",
      label: "Noise Reduction",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether noise reduction is part of the plan."
    },
    {
      key: "debreath_enabled",
      label: "Debreath",
      type: "boolean",
      default_behavior: "Defaults to false.",
      help_text: "Whether breath suppression is enabled."
    },
    {
      key: "loudness_normalization_enabled",
      label: "Loudness Normalization",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether loudness normalization should run."
    },
    {
      key: "target_lufs",
      label: "Target LUFS",
      type: "number",
      default_behavior: "Defaults to -14.",
      help_text: "Target loudness for export."
    },
    {
      key: "music_enabled",
      label: "Music Enabled",
      type: "boolean",
      default_behavior: "Defaults to false.",
      help_text: "Whether background music is allowed."
    },
    {
      key: "music_ducking_enabled",
      label: "Music Ducking",
      type: "boolean",
      default_behavior: "Defaults to true when music is enabled.",
      help_text: "Whether background music should duck under dialogue."
    },
    {
      key: "sfx_enabled",
      label: "SFX Enabled",
      type: "boolean",
      default_behavior: "Defaults to false.",
      help_text: "Whether sound effects are allowed."
    }
  ]),
  ...buildEntries("color_finish", [
    {
      key: "color_polish_enabled",
      label: "Color Polish",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether color polish should run."
    },
    {
      key: "color_style_preset",
      label: "Color Style Preset",
      type: "string",
      default_behavior: "Defaults to clean-cinematic-neutral.",
      help_text: "Color finish preset family."
    },
    {
      key: "lut_enabled",
      label: "LUT Enabled",
      type: "boolean",
      default_behavior: "Defaults to false.",
      help_text: "Whether a LUT is part of the finish plan."
    },
    {
      key: "finish_intensity",
      label: "Finish Intensity",
      type: "enum",
      enum_values: ["light", "medium", "high"],
      default_behavior: "Defaults to light.",
      help_text: "Strength of color and finishing treatments."
    }
  ]),
  ...buildEntries("transitions", [
    {
      key: "transitions_enabled",
      label: "Transitions Enabled",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether transitions are part of the plan."
    },
    {
      key: "transition_style_family",
      label: "Transition Style Family",
      type: "string",
      default_behavior: "Defaults to clean-cut-premium.",
      help_text: "Primary transition language."
    },
    {
      key: "transition_intensity",
      label: "Transition Intensity",
      type: "enum",
      enum_values: ["low", "medium", "high"],
      default_behavior: "Defaults to low.",
      help_text: "How stylized transitions should feel."
    },
    {
      key: "hard_cut_ratio",
      label: "Hard Cut Ratio",
      type: "number",
      default_behavior: "Defaults to 0.85.",
      help_text: "Approximate ratio of hard cuts versus stylized transitions."
    }
  ]),
  ...buildEntries("execution_orchestration", [
    {
      key: "plan_id",
      label: "Plan ID",
      type: "string",
      default_behavior: "Defaults to current job ID.",
      help_text: "Primary identifier for the resolved plan."
    },
    {
      key: "plan_version",
      label: "Plan Version",
      type: "string",
      default_behavior: "Defaults to 1.0.0.",
      help_text: "Version for the generated edit plan."
    },
    {
      key: "execution_graph_version",
      label: "Execution Graph Version",
      type: "string",
      default_behavior: "Defaults to 1.0.0.",
      help_text: "Version for the execution planning graph."
    },
    {
      key: "operation_order",
      label: "Operation Order",
      type: "string[]",
      default_behavior: "Defaults to the fixed v1 pipeline order.",
      help_text: "Resolved top-level operation ordering."
    },
    {
      key: "current_stage",
      label: "Current Stage",
      type: "string",
      default_behavior: "Managed by backend worker.",
      help_text: "Current processing stage for the job."
    },
    {
      key: "stage_history",
      label: "Stage History",
      type: "object",
      default_behavior: "Recorded during processing.",
      help_text: "Timestamped stage transition history."
    },
    {
      key: "warnings",
      label: "Warnings",
      type: "string[]",
      default_behavior: "Defaults to empty.",
      help_text: "Non-blocking issues recorded during planning."
    }
  ]),
  ...buildEntries("fallback", [
    {
      key: "global_fallback_style",
      label: "Global Fallback Style",
      type: "string",
      default_behavior: "Defaults to cinematic-typography-fallback.",
      help_text: "Top-level fallback styling family."
    },
    {
      key: "fallback_typography_preset",
      label: "Fallback Typography Preset",
      type: "string",
      default_behavior: "Defaults to animated-name-card-premium.",
      help_text: "Typography preset used when optional enhancements fail."
    },
    {
      key: "fallback_motion_asset_pack",
      label: "Fallback Motion Pack",
      type: "string",
      default_behavior: "Defaults to minimal-accent-pack.",
      help_text: "Motion pack used when richer motion is unavailable."
    },
    {
      key: "fallback_on_fetch_failure",
      label: "Fetch Failure Fallback",
      type: "string",
      default_behavior: "Defaults to typography-card.",
      help_text: "Fallback action when a source fetch cannot be satisfied."
    },
    {
      key: "fallback_on_bad_transcript",
      label: "Bad Transcript Fallback",
      type: "string",
      default_behavior: "Defaults to lower-enrichment-confidence.",
      help_text: "Fallback action when transcript confidence is poor."
    },
    {
      key: "optional_steps_allowed_to_skip",
      label: "Skippable Optional Steps",
      type: "string[]",
      default_behavior: "Defaults to external_visual_insertion and sfx_enrichment.",
      help_text: "Pipeline steps that may be skipped without failing the job."
    }
  ]),
  ...buildEntries("search_sourcing", [
    {
      key: "keyword_extraction_enabled",
      label: "Keyword Extraction",
      type: "boolean",
      default_behavior: "Defaults to true.",
      help_text: "Whether keyword extraction should run."
    },
    {
      key: "keyword_scoring_mode",
      label: "Keyword Scoring Mode",
      type: "string",
      default_behavior: "Defaults to proportional-threshold.",
      help_text: "Heuristic used to rank source-worthy terms."
    },
    {
      key: "keyword_score_threshold",
      label: "Keyword Score Threshold",
      type: "number",
      default_behavior: "Defaults to 0.65.",
      help_text: "Minimum keyword score for enrichment consideration."
    },
    {
      key: "search_terms_generated",
      label: "Search Terms",
      type: "string[]",
      default_behavior: "Generated from entities and prompt context.",
      help_text: "Potential search terms for future sourcing layers."
    },
    {
      key: "search_term_to_time_map",
      label: "Search Term Timing Map",
      type: "object",
      default_behavior: "Defaults to empty when timings are unavailable.",
      help_text: "Mapping from search terms to transcript timing windows."
    },
    {
      key: "asset_source_priority",
      label: "Asset Source Priority",
      type: "string[]",
      default_behavior: "Defaults to uploaded_assets then external_fetch then typography_fallback.",
      help_text: "Priority order for satisfying visual needs."
    }
  ])
];

export const METADATA_CATALOG_BY_PATH = new Map(
  METADATA_CATALOG_ENTRIES.map((entry) => [entry.key_path, entry])
);

export const METADATA_GROUPS = Array.from(
  new Set(METADATA_CATALOG_ENTRIES.map((entry) => entry.group))
);
